# -*- coding: utf-8 -*-
import datetime
import time

# Form implementation generated from reading ui file 'admission_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRect
from PyQt5.QtGui import QIntValidator

from components.dialog_with_guide import DialogWithGuide
from components.handle_error_message import HandleErrorMessage
from components.top_bar import TopBar
from image_load_page import ImageUploadPage
from utils.common_utils import fetch_data


class PatientAdmissionPage(DialogWithGuide, HandleErrorMessage):
    def __init__(self, parent, registration_id):
        super(PatientAdmissionPage, self).__init__(parent)
        self.setupUi(registration_id)

    def setupUi(self, registration_id):
        self.setObjectName("patientAdmissionPage")
        self.resize(1058, 735)
        self.topBar = TopBar(self, is_menu_visible=True, logout_visible=True)
        self.formLayoutWidget = QtWidgets.QWidget(self)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 170, 921, 271))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.idLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idLabel.setFont(font)
        self.idLabel.setStyleSheet("color:#757575")
        self.idLabel.setObjectName("idLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.idLabel)
        self.idLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.idLineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idLineEdit.setFont(font)
        self.idLineEdit.setStyleSheet("color:#757575")
        self.idLineEdit.setObjectName("idLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.idLineEdit)
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("color:#757575")
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.bedLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bedLabel.setFont(font)
        self.bedLabel.setStyleSheet("color:#757575")
        self.bedLabel.setObjectName("bedLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bedLabel)
        self.reasonLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reasonLabel.setFont(font)
        self.reasonLabel.setStyleSheet("color:#757575")
        self.reasonLabel.setObjectName("reasonLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.reasonLabel)
        self.reasonLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reasonLineEdit.setFont(font)
        self.reasonLineEdit.setStyleSheet("color:#757575")
        self.reasonLineEdit.setObjectName("reasonLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.reasonLineEdit)
        self.doctorLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doctorLabel.setFont(font)
        self.doctorLabel.setStyleSheet("color:#757575")
        self.doctorLabel.setObjectName("doctorLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.doctorLabel)
        self.doctorLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doctorLineEdit.setFont(font)
        self.doctorLineEdit.setAutoFillBackground(True)
        self.doctorLineEdit.setStyleSheet("color:#757575")
        self.doctorLineEdit.setObjectName("doctorLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.doctorLineEdit)
        self.bedLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bedLineEdit.setFont(font)
        self.bedLineEdit.setStyleSheet("color:#757575")
        self.bedLineEdit.setObjectName("bedLineEdit")
        int_validator = QIntValidator(self)
        self.bedLineEdit.setValidator(int_validator)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bedLineEdit)
        self.nameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nameLineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setStyleSheet("color:#757575")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(40, 130, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 170, 255); font-weight:bold")
        self.label.setObjectName("label")
        self.addButton = QtWidgets.QPushButton(self)
        self.addButton.setGeometry(QtCore.QRect(40, 460, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 170, 255)")
        self.addButton.setObjectName("addButton")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.addErrorLabel(QRect(40, 170, 201, 21), self)
        self.setValues(registration_id)
        self.addButton.clicked.connect(lambda: self.add_admission(registration_id))
        self.topBar.loginButton.clicked.connect(self.gotoHome)
        self.topBar.menuButton.clicked.connect(self.goToMenu)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("patientAdmissionPage", "Infant Pose Visualizer"))
        self.idLabel.setText(_translate("patientAdmissionPage", "Registration ID"))
        self.nameLabel.setText(_translate("patientAdmissionPage", "Name"))
        self.bedLabel.setText(_translate("patientAdmissionPage", "Admitted Bed<sup>*</sup>"))
        self.reasonLabel.setText(_translate("patientAdmissionPage", "Reason for Admission<sup>*</sup>"))
        self.doctorLabel.setText(_translate("patientAdmissionPage", "Doctor In-charge<sup>*</sup>"))
        self.label.setText(_translate("patientAdmissionPage", "Admission Details"))
        self.addButton.setText(_translate("patientAdmissionPage", "Add"))

    def setValues(self, registration_id):
        try:
            data = fetch_data("patients/data", {"_id": registration_id})
            self.idLineEdit.setText(str(registration_id))
            self.nameLineEdit.setText(data["patient_name"])
        except Exception as e:
            self.displayErrorMessage(True, "Error fetching data")

    def add_admission(self, registration_id):
        admitted_time = time.time_ns()
        admitted_bed = self.bedLineEdit.text()
        admitted_reason = self.reasonLineEdit.text()
        doctor = self.doctorLineEdit.text()
        data = {
            "admitted_time": admitted_time,
            "admitted_bed": admitted_bed,
            "admitted_reason": admitted_reason,
            "doctor": doctor,
            "patient_id": registration_id
        }
        print(data)
        if self.handlePostRequest("patients/admission", data):
            self.stack_image_upload_page(registration_id)

    def stack_image_upload_page(self, registration_id):
        image_upload_page = ImageUploadPage(self.parent, registration_id)
        self.parent.addWidget(image_upload_page)
        self.parent.setCurrentIndex(self.parent.currentIndex() + 1)
