# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guide_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

from components.top_bar import TopBar


class GuideDialog(QtWidgets.QDialog):
    def __init__(self):
        super(GuideDialog, self).__init__()
        self.setupUi()
    def setupUi(self):
        self.setObjectName("guideDialog")
        self.setWindowFlags(self.windowFlags() | Qt.Tool)
        self.resize(1058, 735)
        self.topBar = TopBar(self)
        self.guideBox = QtWidgets.QToolBox(self)
        self.guideBox.setGeometry(QtCore.QRect(90, 150, 921, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guideBox.sizePolicy().hasHeightForWidth())
        self.guideBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.guideBox.setFont(font)
        self.guideBox.setStyleSheet("color: rgb(0, 170, 255)")
        self.guideBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.guideBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.guideBox.setObjectName("guideBox")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setGeometry(QtCore.QRect(0, 0, 921, 132))
        self.page_1.setObjectName("page_1")
        self.textEdit = QtWidgets.QTextEdit(self.page_1)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 921, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit.setObjectName("textEdit")
        self.guideBox.addItem(self.page_1, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 921, 132))
        self.page_2.setObjectName("page_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.page_2)
        self.textEdit_2.setEnabled(True)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 0, 921, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_2.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.textEdit_2.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit_2.setObjectName("textEdit_2")
        self.guideBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.textEdit_5 = QtWidgets.QTextEdit(self.page_3)
        self.textEdit_5.setEnabled(True)
        self.textEdit_5.setGeometry(QtCore.QRect(0, 0, 921, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_5.sizePolicy().hasHeightForWidth())
        self.textEdit_5.setSizePolicy(sizePolicy)
        self.textEdit_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_5.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.textEdit_5.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit_5.setObjectName("textEdit_5")
        self.guideBox.addItem(self.page_3, "")

        self.retranslateUi()
        self.guideBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("guideDialog", "Dialog"))
        self.textEdit.setHtml(_translate("guideDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:12pt;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#757575;\">Login using the provided credential as a medical staff member.</span></li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select <span style=\" font-style:italic;\">Register a Patient</span> and Register the patients by providing relevant infoemation.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Upload the depth and pressure images of the pose of the patient under investigation.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can now vizualise the pose of the infant.</li></ol></body></html>"))
        self.guideBox.setItemText(self.guideBox.indexOf(self.page_1), _translate("guideDialog", "Patient registration and Pose visualization"))
        self.textEdit_2.setHtml(_translate("guideDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:12pt;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#757575;\">Login using the provided credential as a medical staff member.</span></li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select <span style=\" font-style:italic;\">View Pose Estimation</span> and  and Search for the patient under investigation using name.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Upload the depth and pressure images of the pose of the patient under investigation.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can now visualize the pose of the infant.</li></ol></body></html>"))
        self.guideBox.setItemText(self.guideBox.indexOf(self.page_2), _translate("guideDialog", "Pose visualization of a registred patient"))
        self.textEdit_5.setHtml(_translate("guideDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:12pt;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#757575;\">Login using the provided credential as a medical staff member.</span></li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select <span style=\" font-style:italic;\">View Pose Estimation</span> and  and Search for the patient under investigation using name.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Upload the depth and pressure images of the pose of the patient under investigation.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can now visualize the pose of the infant.</li></ol></body></html>"))
        self.guideBox.setItemText(self.guideBox.indexOf(self.page_3), _translate("guideDialog", "Page"))
