# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'landing_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QDialog

from login_page import LoginPage
from components.top_bar import TopBar


class HomeWindow(QDialog):
    def __init__(self, parent=None):
        super(HomeWindow, self).__init__()
        self.parent = parent
        self.setupUi()

    def setupUi(self):
        self.setObjectName("mainWindow")
        self.setEnabled(True)
        self.resize(1058, 735)
        self.setMinimumSize(QtCore.QSize(1058, 735))
        self.setMaximumSize(QtCore.QSize(1058, 735))
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.topBar = TopBar(self.centralwidget, True)
        self.introText = QtWidgets.QTextEdit(self.centralwidget)
        self.introText.setGeometry(QtCore.QRect(20, 120, 1021, 201))
        self.introText.setObjectName("introText")
        self.introText.setReadOnly(True)
        self.helpText = QtWidgets.QTextEdit(self.centralwidget)
        self.helpText.setGeometry(QtCore.QRect(20, 330, 1021, 361))
        self.helpText.setObjectName("helpText")
        self.helpText.setReadOnly(True)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.topBar.loginButton.clicked.connect(self.gotoLogin)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("mainWindow", "Infant Pose Visualizer"))
        self.introText.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#757575;\">Welcome to Infant Pose Visualiser !</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#757575;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:25px;\"><span style=\" font-size:12pt; color:#757575;\">This is aframework where infants (from birth up to 12 months) who are lying on the beds are captured via cameras or sensors as videos or images and the captured images are analyzed to generate the pose of the infants as 2D skeleton as shown in the image. This eliminates the requirement of the staff to ensure that the infants are in safe position all the time and also eliminates the cost for installing video cameras to monitor the infant motions. Also note that the identity of the infant who is being monitored is not disclosed, securing his/her privacy, since the system uses depth and pressure images captured via depth cameras and sensors on pressure mats. </span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#757575;\"><br /></p></body></html>"))
        self.helpText.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#757575;\">How to use the system ?</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#757575;\"><br /></p>\n"
                                                       
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:10px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic; color:#757575;\">Patient registration and Pose visualization</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:12pt;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#757575;\">Login using the provided credential as a medical staff member.</span></li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select <span style=\" font-style:italic;\">Register a Patient.</span></li>\n"
"<li style=\" font-size:12pt; fon"
"t-style:italic; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">Register the patients by providing relevant information. If the registration was a success, a registration id will be issued. </span><span style=\" font-style:normal; color:#754b4b;\">NOTE: Please ask the patients to present the registered id in their next visit.</span></li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Upload the depth and pressure images of the pose of the patient under investigation. Here you have to select the folder containing depth and pressure images in &quot;.npy&quot; format.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:"
"0; text-indent:0px;\">The uploaded images will be visualized, if the input images are in correct format.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Click <span style=\" font-style:italic;\">Process </span>to view the pose estimation.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Once the pose estimation is visible, you can optionally provide any medical remarks and feedback about the prediction as well. To add a medical remark, type the content in the given text box beside the pose visualization and save it by clicking <span style=\" font-style:italic;\">Save</span>. To give a feedback about the prediction click <span style=\" font-style:italic;\">Provide feedback on this prediction </span>and<span style=\" font-style:italic;\"> </span>in the appearing popup, type the content and click <span style=\" font-style:italic;\">Submit</span> to save it.</li></ol>\n"
"<br>"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:10px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic; color:#757575;\">Pose visualization of a Registred Patient</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:12pt;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#757575;\">Login using the provided credential as a medical staff member.</span></li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select <span style=\" font-style:italic;\">View Pose Estimation.</span></li>\n"
"<li style=\" font-size:12pt; font-style:italic; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">Search for the patient under investigation using name/registered id.</span></li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Upload the depth and pressure images of the pose of the patient under investigation. Here you have to select the folder containing depth and pressure images in &quot;.npy&quot; format.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The uploaded images will be visualized, if the input images are in correct format.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-"
"top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Click <span style=\" font-style:italic;\">Process </span>to view the pose estimation.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Once the pose estimation is visible, you can optionally provide any medical remarks and feedback about the prediction as well. To add a medical remark, type the content in the given text box beside the pose visualization and save it by clicking <span style=\" font-style:italic;\">Save</span>. To give a feedback about the prediction click <span style=\" font-style:italic;\">Provide feedback on this prediction </span>and<span style=\" font-style:italic;\"> </span>in the appearing popup, type the content and click <span style=\" font-style:italic;\">Submit</span> to save it.</li></ol>\n"
"<br>"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:10px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic; color:#757575;\">View Historical Data</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:12pt;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#757575;\">Login using the provided credential as a medical staff member.</span></li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select <span style=\" font-style:italic;\">View Historical Data.</span></li>\n"
"<li style=\" font-size:12pt; f"
"ont-style:italic; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">Search for the patient whose data you want to view using name/registered Id.</span></li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select a date range for visualization.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Click <span style=\" font-style:italic;\">View </span>and if there are any data to show, they will be shown.</li></ol>\n"
"<br>"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:10px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic; color:#757575;\">Edit Patient Data</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:15px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#757575;\">There are </span><span style=\" font-size:12pt; color:#754b4b;\">two ways</span><span style=\" font-size:12pt; color:#757575;\"> of accessing this functionality.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:15px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; text-decoration: underline; color:#757575;\">Method 1</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-ri"
"ght: 0px; -qt-list-indent: 1;\"><li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select <span style=\" font-style:italic;\">View Pose Estimation.</span></li>\n"
"<li style=\" font-size:12pt; font-style:italic; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">Search for the patient whose data you want to edit using name/registered Id.</span></li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select <span style=\" font-style:italic;\">Edit Patient</span>.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px"
"; -qt-block-indent:0; text-indent:0px;\">Edit any required fields and click <span style=\" font-style:italic;\">Save </span>to save data or click <span style=\" font-style:italic;\">Cancel</span> to cancel operation.</li></ol>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:15px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; text-decoration: underline; color:#757575;\">Method 2</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select <span style=\" font-style:italic;\">View Historical Data.</span></li>\n"
"<li style=\" font-size:12pt; font-style:italic; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0;"
" text-indent:0px;\"><span style=\" font-style:normal;\">Search for the patient whose data you want to edit using name/registered Id and click </span>View.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select <span style=\" font-style:italic;\">Edit Patient </span>at the bottom of the page.</li>\n"
"<li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Edit any required fields and click <span style=\" font-style:italic;\">Save </span>to save data or click <span style=\" font-style:italic;\">Cancel</span> to cancel operation.</li></ol>\n"
"<br>"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:10px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic; color:#757575;\">Give Feedback</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:15px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#757575;\">You can provide a feedback about the overall system or a feedback on specific pose estimations.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:15px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; text-decoration: underline; color:#757575;\">Provide feedback about the overall system</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><"
"li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">On the <span style=\" font-style:italic;\">Menu Page</span> select <span style=\" font-style:italic;\">Provide feedback</span>.</li>\n"
"<li style=\" font-size:12pt; font-style:italic; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:normal;\">Type the content and click </span>Submit<span style=\" font-style:normal;\"> to save the feedback.</span></li></ol>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:15px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; text-decoration: underline; color:#757575;\">Provide feedback on specific pose estimations</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; marg"
"in-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:12pt; color:#757575;\" align=\"justify\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">When you are viewing a pose estimation, click <span style=\" font-style:italic;\">Provide feedback on this prediction </span>and<span style=\" font-style:italic;\"> </span>in the appearing popup, type the content and click <span style=\" font-style:italic;\">Submit</span> to save it.</li></ol>"
"<br></body></html>"))

    def gotoLogin(self):
        login = LoginPage(self.parent)
        self.parent.addWidget(login)
        self.parent.setCurrentIndex(self.parent.count() - 1)




