# -*- coding: utf-8 -*-
import time

import numpy as np
# Form implementation generated from reading ui file 'image_load_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRect

from components.dialog_with_guide import DialogWithGuide
from components.handle_error_message import HandleErrorMessage
from components.matplotlib_canvas import MatplotlibCanvas
from components.top_bar import TopBar
from pose_visualization_page import PoseVisualizationPage
from utils.common_utils import fetch_data, get_prediction


class ImageUploadPage(DialogWithGuide, HandleErrorMessage):
    def __init__(self, parent, registration_id):
        super(ImageUploadPage, self).__init__(parent)
        self.images = {}
        self.input_validation_errors = []
        self.setupUi(registration_id)

    def setupUi(self, registration_id):
        self.setObjectName("imageUploadPage")
        self.resize(1058, 735)
        self.topBar = TopBar(self, is_menu_visible=True, logout_visible=True)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(40, 130, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 170, 255); font-weight:bold")
        self.label.setObjectName("label")
        self.uploadButton = QtWidgets.QPushButton(self)
        self.uploadButton.setGeometry(QtCore.QRect(40, 620, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uploadButton.setFont(font)
        self.uploadButton.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 170, 255)")
        self.uploadButton.setObjectName("uploadButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 200, 941, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(17)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pressureUploadButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pressureUploadButton.setFont(font)
        self.pressureUploadButton.setStyleSheet("color:#757575")
        self.pressureUploadButton.setObjectName("pressureUploadButton")
        self.gridLayout.addWidget(self.pressureUploadButton, 1, 2, 1, 1)
        self.pressureFileLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.pressureFileLineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pressureFileLineEdit.setFont(font)
        self.pressureFileLineEdit.setObjectName("pressureFileLineEdit")
        self.gridLayout.addWidget(self.pressureFileLineEdit, 1, 1, 1, 1)
        self.pressureLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pressureLabel.setFont(font)
        self.pressureLabel.setStyleSheet("color:#757575")
        self.pressureLabel.setObjectName("pressureLabel")
        self.gridLayout.addWidget(self.pressureLabel, 1, 0, 1, 1)
        self.depthFileLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.depthFileLineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.depthFileLineEdit.setFont(font)
        self.depthFileLineEdit.setObjectName("depthFileLineEdit")
        self.gridLayout.addWidget(self.depthFileLineEdit, 0, 1, 1, 1)
        self.depthUploadButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.depthUploadButton.setFont(font)
        self.depthUploadButton.setStyleSheet("color:#757575")
        self.depthUploadButton.setObjectName("depthUploadButton")
        self.gridLayout.addWidget(self.depthUploadButton, 0, 2, 1, 1)
        self.depthLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.depthLabel.setFont(font)
        self.depthLabel.setStyleSheet("color:#757575")
        self.depthLabel.setObjectName("depthLabel")
        self.gridLayout.addWidget(self.depthLabel, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 280, 941, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.labelLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.labelLayout.setContentsMargins(0, 0, 0, 0)
        self.labelLayout.setObjectName("labelLayout")
        self.depthLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.depthLabel_2.setFont(font)
        self.depthLabel_2.setStyleSheet("color:#757575")
        self.depthLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.depthLabel_2.setObjectName("depthLabel_2")
        self.labelLayout.addWidget(self.depthLabel_2)
        self.pressureLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pressureLabel_2.setFont(font)
        self.pressureLabel_2.setStyleSheet("color:#757575")
        self.pressureLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.pressureLabel_2.setObjectName("pressureLabel_2")
        self.labelLayout.addWidget(self.pressureLabel_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 320, 941, 281))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setMinimumSize(QtCore.QSize(467, 279))
        self.label_5.setMaximumSize(QtCore.QSize(467, 279))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:#757575")
        self.label_5.setObjectName("label_5")
        self.depthCanvas = MatplotlibCanvas(self.label_5)
        self.horizontalLayout_3.addWidget(self.depthCanvas)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setMinimumSize(QtCore.QSize(466, 279))
        self.label_6.setMaximumSize(QtCore.QSize(466, 279))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:#757575")
        self.label_6.setObjectName("label_6")
        self.pressureCanvas = MatplotlibCanvas(self.label_6)
        self.horizontalLayout_3.addWidget(self.pressureCanvas)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(40, 160, 941, 41))
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.idLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.idLineEdit.setObjectName(u"idLineEdit")
        self.idLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idLineEdit.sizePolicy().hasHeightForWidth())
        self.idLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idLineEdit.setFont(font)
        self.gridLayout_2.addWidget(self.idLineEdit, 0, 1, 1, 1)
        self.idLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.idLabel.setObjectName(u"idLabel")
        self.idLabel.setFont(font)
        self.idLabel.setStyleSheet(u"color:#757575")
        self.gridLayout_2.addWidget(self.idLabel, 0, 0, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.nameLineEdit.setObjectName(u"nameLineEdit")
        self.nameLineEdit.setEnabled(False)
        self.nameLineEdit.setFont(font)
        self.gridLayout_2.addWidget(self.nameLineEdit, 0, 3, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.nameLabel.setObjectName(u"nameLabel")
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet(u"color:#757575")

        self.gridLayout_2.addWidget(self.nameLabel, 0, 2, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.setValues(registration_id)
        self.addErrorLabel(QRect(40, 170, 201, 21), self)
        self.topBar.loginButton.clicked.connect(self.gotoHome)
        self.topBar.menuButton.clicked.connect(self.goToMenu)

        self.depthUploadButton.clicked.connect(lambda: self.upload_file_and_display("depth"))
        self.pressureUploadButton.clicked.connect(lambda: self.upload_file_and_display("pressure"))
        self.uploadButton.clicked.connect(lambda: self.process_images(registration_id))

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("imageUploadPage", "Dialog"))
        self.label.setText(_translate("imageUploadPage", "Upload Images"))
        self.uploadButton.setText(_translate("imageUploadPage", "Process"))
        self.pressureUploadButton.setText(_translate("imageUploadPage", "Upload"))
        self.pressureLabel.setText(_translate("imageUploadPage", "Pressure image<sup>*</sup>"))
        self.depthUploadButton.setText(_translate("imageUploadPage", "Upload"))
        self.depthLabel.setText(_translate("imageUploadPage", "Depth image<sup>*</sup>"))
        self.depthLabel_2.setText(_translate("imageUploadPage", "Depth image"))
        self.pressureLabel_2.setText(_translate("imageUploadPage", "Pressure image"))
        self.nameLabel.setText(_translate("imageUploadPage", "Name"))
        self.idLabel.setText(_translate("imageUploadPage", "Registration ID"))

    def upload_file_and_display(self, modality):
        if len(self.input_validation_errors) == 0:
            self.displayErrorMessage(False)
        try:
            options = QtWidgets.QFileDialog.Options()
            options |= QtWidgets.QFileDialog.ReadOnly
            fileName, _ = QtWidgets.QFileDialog.getOpenFileName(self, "QFileDialog.getOpenFileName()", "",
                                                                "NumPy Files (*.npy)", options=options)
            if fileName:
                np_array = np.load(fileName)
                if modality == "depth":
                    self.depthFileLineEdit.setText(fileName)
                    self.depthCanvas.axes.clear()
                    if np_array.dtype != np.uint16:
                        self.handle_image_input_validation(modality)
                        return
                    self.depthCanvas.axes.imshow(np_array)
                    self.depthCanvas.draw()
                elif modality == "pressure":
                    self.pressureFileLineEdit.setText(fileName)
                    self.pressureCanvas.axes.clear()
                    if np_array.dtype != np.float32:
                        self.handle_image_input_validation(modality)
                        return
                    self.pressureCanvas.axes.imshow(np_array)
                    self.pressureCanvas.draw()
                self.images[modality] = np_array
                self.handle_image_input_validation(modality, True)
        except Exception as e:
            self.displayErrorMessage(True, "Error occurred: " + str(e))

    def setValues(self, registration_id):
        try:
            data = fetch_data("patients/data", {"_id": registration_id})
            self.idLineEdit.setText(str(registration_id))
            self.nameLineEdit.setText(data["patient_name"])
        except Exception as e:
            self.displayErrorMessage(True, "Error fetching data: " + str(e))

    def process_images(self, registration_id):
        if len(self.input_validation_errors) == 0:
            self.displayErrorMessage(False)
            now_time = time.time_ns()
            data = {
                "patient_id": registration_id,
                "depth": None,
                "pressure": None,
                "time": now_time
            }
            if len(self.images) != 2:
                self.displayErrorMessage(True, "Inputs marked with * are required")
            else:
                for modality in self.images:
                    data[modality] = self.images[modality].tolist()
                response = get_prediction("patients/prediction", data)
                if type(response) is str:
                    self.displayErrorMessage(True, response)
                else:
                    self.stack_pose_visualization_page(registration_id, now_time, response)

    def stack_pose_visualization_page(self, registration_id, now_time, response):
        pose_visualization_page = PoseVisualizationPage(self.parent, registration_id, now_time, response)
        self.parent.addWidget(pose_visualization_page)
        self.parent.setCurrentIndex(self.parent.currentIndex() + 1)

    def handle_image_input_validation(self, modality, remove_message=False):
        modality_in_list = len([s for s in self.input_validation_errors if modality in s]) != 0
        error_message = modality + " image is not in accepted format."
        if remove_message:
            if modality_in_list:
                self.input_validation_errors.remove(error_message)
            else:
                return
        else:
            if not modality_in_list:
                self.input_validation_errors.append(error_message)
        if len(self.input_validation_errors) == 0:
            self.displayErrorMessage(False)
        else:
            self.displayErrorMessage(True, " ".join(self.input_validation_errors))
