# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRect, Qt
from PyQt5.QtGui import QFont

from components.handle_error_message import HandleErrorMessage
from components.top_bar import TopBar
from menu_page import MenuPage
from utils.common_utils import sendPostRequest, has_empty_or_null_value


class LoginPage(QtWidgets.QDialog, HandleErrorMessage):
    def __init__(self, parent):
        super(LoginPage, self).__init__()
        self.parent = parent
        self.setupUi()

    def setupUi(self):
        self.setObjectName("LoginPage")
        self.resize(1058, 735)
        self.setMinimumSize(QtCore.QSize(1058, 735))
        self.setMaximumSize(QtCore.QSize(1058, 735))
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.topBar = TopBar(self.centralwidget, is_home_accessible=True)
        self.loginWidget = QtWidgets.QWidget(self.centralwidget)
        self.loginWidget.setGeometry(QtCore.QRect(250, 180, 521, 411))
        self.loginWidget.setAutoFillBackground(False)
        self.loginWidget.setStyleSheet("background-color : rgb(0, 170, 255)")
        self.loginWidget.setObjectName("loginWidget")
        self.loginLabel = QtWidgets.QLabel(self.loginWidget)
        self.loginLabel.setGeometry(QtCore.QRect(230, 30, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("font-weight: bold; color: rgb(255, 255, 255)")
        self.loginLabel.setObjectName("loginLabel")
        self.formLayoutWidget = QtWidgets.QWidget(self.loginWidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(110, 90, 317, 251))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.loginFormLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.loginFormLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.loginFormLayout.setContentsMargins(0, 0, 0, 0)
        self.loginFormLayout.setHorizontalSpacing(42)
        self.loginFormLayout.setVerticalSpacing(17)
        self.loginFormLayout.setObjectName("loginFormLayout")
        self.medicalStaffOption = QtWidgets.QRadioButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.medicalStaffOption.setFont(font)
        self.medicalStaffOption.setStyleSheet("color: rgb(255, 255, 255)")
        self.medicalStaffOption.setObjectName("medicalStaffOption")
        self.loginFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.medicalStaffOption)
        self.systemAdminOption = QtWidgets.QRadioButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.systemAdminOption.setFont(font)
        self.systemAdminOption.setStyleSheet("color: rgb(255, 255, 255)")
        self.systemAdminOption.setObjectName("systemAdminOption")
        self.loginFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.systemAdminOption)
        self.usernameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.usernameInput.setFont(font)
        self.usernameInput.setStyleSheet("background-color: rgb(255, 255, 255); color: #757575")
        self.usernameInput.setObjectName("usernameInput")
        self.loginFormLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.usernameInput)
        self.passwordInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passwordInput.setFont(font)
        self.passwordInput.setStyleSheet("background-color: rgb(255, 255, 255); color: #757575")
        self.passwordInput.setObjectName("passwordInput")
        self.loginFormLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.passwordInput)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setStyleSheet("color: rgb(255, 255, 255)")
        self.passwordLabel.setObjectName("passwordLabel")
        self.loginFormLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.passwordLabel)
        self.usernameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setStyleSheet("color: rgb(255, 255, 255)")
        self.usernameLabel.setObjectName("usernameLabel")
        self.loginFormLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.usernameLabel)
        self.loginButton = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 170, 255)")
        self.loginButton.setObjectName("loginButton")
        self.loginFormLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.loginButton)
        self.addErrorLabel(QRect(90, 80, 241, 21), self.loginWidget)
        self.topBar.mainLabel.clicked.connect(self.label_clicked)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.loginButton.clicked.connect(self.loginFunction)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("LoginPage", "Infant Pose Visualizer"))
        self.loginLabel.setText(_translate("LoginPage", "Login"))
        self.medicalStaffOption.setText(_translate("LoginPage", "Medical Staff"))
        self.systemAdminOption.setText(_translate("LoginPage", "System Admin"))
        self.passwordLabel.setText(_translate("LoginPage", "Password<sup>*</sup>"))
        self.usernameLabel.setText(_translate("LoginPage", "Username<sup>*</sup>"))
        self.loginButton.setText(_translate("LoginPage", "Login"))

    def loginFunction(self):
        username = self.usernameInput.text()
        password = self.passwordInput.text()
        user_type = 0
        if self.medicalStaffOption.isChecked(): user_type = 1
        if self.systemAdminOption.isChecked(): user_type = 2
        data = {
            "username": username,
            "password": password,
            "user_type": user_type
        }
        if self.handlePostRequest("users/auth", data):
            self.stack_menu_page()

    def label_clicked(self):
        self.parent.setCurrentIndex(0)

    def stack_menu_page(self):
        menuPage = MenuPage(self.parent)
        self.parent.addWidget(menuPage)
        # self.parent.setCurrentIndex(self.parent.currentIndex()+1)
        for i in range(self.parent.count()):
            widget = self.parent.widget(i)
            if widget.objectName() == "menuPage":
                self.parent.setCurrentIndex(i)
                break
