# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model_details_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ModelDetailsPage(QtWidgets.QDialog):
    def __init__(self, model_details=None, parent=None):
        super(ModelDetailsPage, self).__init__(parent)
        self.parent = parent
        self.model_details = model_details
        self.setupUi()

    def setupUi(self):
        self.setObjectName("ModelDetailsPage")
        self.resize(482, 406)
        self.modelDetailsLabel = QtWidgets.QLabel(self)
        self.modelDetailsLabel.setGeometry(QtCore.QRect(30, 30, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.modelDetailsLabel.setFont(font)
        self.modelDetailsLabel.setStyleSheet("color:#757575")
        self.modelDetailsLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.modelDetailsLabel.setObjectName("modelDetailsLabel")
        self.textEdit = QtWidgets.QTextEdit(self)
        self.textEdit.setGeometry(QtCore.QRect(30, 70, 411, 301))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("color:#757575")


        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("ModelDetailsPage", "ModelDetailsPage"))
        self.modelDetailsLabel.setText(_translate("ModelDetailsPage", "Model Details"))
        details = """<style>
                                            li {
                                                margin-bottom: 10px;
                                            }
                                        </style>
                                        <ul>"""
        for key in self.model_details:
            if key == "_id":
                details += "<li>id : " + str(self.model_details[key]["$oid"])
            else:
                details += "<li>" + str(key) + " : " + str(self.model_details[key]) + "</li>"
        details += "</ul>"
        self.textEdit.setHtml(details)
