# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patient_registration_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRect, QDate, QDateTime
from PyQt5.QtGui import QIntValidator

from components.dialog_with_guide import DialogWithGuide
from components.handle_error_message import HandleErrorMessage
from components.top_bar import TopBar
from registration_success import RegistrationSuccessPopup


class PatientRegistrationPage(DialogWithGuide, HandleErrorMessage):
    def __init__(self, parent, user):
        super(PatientRegistrationPage, self).__init__(parent)
        self.user = user
        self.setupUi()

    def setupUi(self):
        self.setObjectName("patientRegistrationPage")
        self.resize(1058, 735)
        self.topBar = TopBar(self, is_menu_visible=True, logout_visible=True, user=self.user)
        self.formLayoutWidget = QtWidgets.QWidget(self)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 170, 921, 296))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("color:#757575")
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.nameLineEdit.setStyleSheet("color:#757575")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.genderLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.genderLabel.setFont(font)
        self.genderLabel.setStyleSheet("color:#757575")
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.genderLabel)
        self.genderComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.genderComboBox.setFont(font)
        self.genderComboBox.setStyleSheet("color:#757575")
        self.genderComboBox.setObjectName("genderComboBox")
        self.genderComboBox.addItem("")
        self.genderComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.genderComboBox)
        self.dateOfBirthLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateOfBirthLabel.setFont(font)
        self.dateOfBirthLabel.setStyleSheet("color:#757575")
        self.dateOfBirthLabel.setObjectName("dateOfBirthLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dateOfBirthLabel)
        self.dateOfBirthDateEdit = QtWidgets.QDateEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateOfBirthDateEdit.setFont(font)
        self.dateOfBirthDateEdit.setStyleSheet("color:#757575")
        self.dateOfBirthDateEdit.setObjectName("dateOfBirthDateEdit")
        self.dateOfBirthDateEdit.setCalendarPopup(True)
        current_date = QDate.currentDate()
        self.dateOfBirthDateEdit.setMaximumDate(current_date)
        fifteen_months_ago = current_date.addMonths(-15)
        self.dateOfBirthDateEdit.setMinimumDate(fifteen_months_ago)
        self.dateOfBirthDateEdit.setDate(current_date)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateOfBirthDateEdit)
        self.gardianSNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gardianSNameLabel.setFont(font)
        self.gardianSNameLabel.setStyleSheet("color:#757575")
        self.gardianSNameLabel.setObjectName("gardianSNameLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gardianSNameLabel)
        self.gardianSNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gardianSNameLineEdit.setFont(font)
        self.gardianSNameLineEdit.setStyleSheet("color:#757575")
        self.gardianSNameLineEdit.setObjectName("gardianSNameLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gardianSNameLineEdit)
        self.addressLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addressLabel.setFont(font)
        self.addressLabel.setStyleSheet("color:#757575")
        self.addressLabel.setObjectName("addressLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.addressLabel)
        self.addressLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addressLineEdit.setFont(font)
        self.addressLineEdit.setStyleSheet("color:#757575")
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.addressLineEdit)
        self.contactNumberLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contactNumberLabel.setFont(font)
        self.contactNumberLabel.setStyleSheet("color:#757575")
        self.contactNumberLabel.setObjectName("contactNumberLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.contactNumberLabel)
        self.contactNumberLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contactNumberLineEdit.setFont(font)
        self.contactNumberLineEdit.setStyleSheet("color:#757575")
        self.contactNumberLineEdit.setObjectName("contactNumberLineEdit")
        int_validator = QIntValidator(self)
        self.contactNumberLineEdit.setValidator(int_validator)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.contactNumberLineEdit)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(40, 130, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 170, 255); font-weight:bold")
        self.label.setObjectName("label")
        self.registerButton = QtWidgets.QPushButton(self)
        self.registerButton.setGeometry(QtCore.QRect(40, 490, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.registerButton.setFont(font)
        self.registerButton.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 170, 255)")
        self.registerButton.setObjectName("registerButton")
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.addErrorLabel(QRect(40, 170, 201, 21), self)
        self.registerButton.clicked.connect(self.register_patient)
        self.topBar.loginButton.clicked.connect(self.gotoHome)
        self.topBar.menuButton.clicked.connect(self.goToMenu)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("patientRegistrationPage", "Dialog"))
        self.nameLabel.setText(_translate("patientRegistrationPage", "Name<sup>*</sup>"))
        self.genderLabel.setText(_translate("patientRegistrationPage", "Gender<sup>*</sup>"))
        self.genderComboBox.setItemText(0, _translate("patientRegistrationPage", "Male"))
        self.genderComboBox.setItemText(1, _translate("patientRegistrationPage", "Female"))
        self.dateOfBirthLabel.setText(_translate("patientRegistrationPage", "Date of Birth<sup>*</sup>"))
        self.gardianSNameLabel.setText(_translate("patientRegistrationPage", "Guardian\'s Name<sup>*</sup>"))
        self.addressLabel.setText(_translate("patientRegistrationPage", "Address<sup>*</sup>"))
        self.contactNumberLabel.setText(_translate("patientRegistrationPage", "Contact Number<sup>*</sup>"))
        self.label.setText(_translate("patientRegistrationPage", "Patient Registration"))
        self.registerButton.setText(_translate("patientRegistrationPage", "Register"))


    def register_patient(self):
        patient_name = self.nameLineEdit.text()
        gender = self.genderComboBox.currentText()
        date_of_birth = self.dateOfBirthDateEdit.date()
        guardian = self.gardianSNameLineEdit.text()
        address = self.addressLineEdit.text()
        contact_number = self.contactNumberLineEdit.text()
        data = {
            "patient_name" : patient_name,
            "gender" : gender,
            "date_of_birth": date_of_birth.toString("yyyy-MM-dd"),
            "guardian": guardian,
            "address" : address,
            "contact_number" : contact_number,
            # "admitted_time": admitted_time.toString("yyyy-MM-dd HH:mm:ss"),
            # "admitted_bed" : admitted_bed,
            # "admitted_reason" : admitted_reason,
        }
        response = self.handlePostRequest("patients/registration", data, True)
        if response:self.show_popup(response)

    def show_popup(self, response):
        popup = RegistrationSuccessPopup(response, self.user, self)
        popup.show()