# -*- coding: utf-8 -*-
import time

# Form implementation generated from reading ui file 'pose_visualization_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRect, QByteArray
from PyQt5.QtGui import QPixmap

from components.clickable_label import ClickableLabel
from components.dialog_with_guide import DialogWithGuide
from components.handle_error_message import HandleErrorMessage
from components.top_bar import TopBar
from utils.common_utils import fetch_data


class PoseVisualizationPage(DialogWithGuide, HandleErrorMessage):

    def __init__(self, parent, registration_id, now_time, response):
        super(PoseVisualizationPage, self).__init__(parent)
        self.images={}
        self.setupUi(registration_id, now_time, response)

    def setupUi(self, registration_id, now_time, response):
        self.setObjectName("poseVisualizationPage")
        self.resize(1058, 735)
        self.topBar = TopBar(self, is_menu_visible=True, logout_visible=True)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(40, 130, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 170, 255); font-weight:bold")
        self.label.setObjectName("label")
        self.uploadButton = QtWidgets.QPushButton(self)
        self.uploadButton.setGeometry(QtCore.QRect(480, 500, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uploadButton.setFont(font)
        self.uploadButton.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 170, 255)")
        self.uploadButton.setObjectName("uploadButton")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 170, 941, 41))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.timeLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.timeLineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeLineEdit.setFont(font)
        self.timeLineEdit.setObjectName("timeLineEdit")
        self.gridLayout_2.addWidget(self.timeLineEdit, 0, 5, 1, 1)
        self.idLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.idLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idLineEdit.sizePolicy().hasHeightForWidth())
        self.idLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idLineEdit.setFont(font)
        self.idLineEdit.setObjectName("idLineEdit")
        self.gridLayout_2.addWidget(self.idLineEdit, 0, 1, 1, 1)
        self.idLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idLabel.setFont(font)
        self.idLabel.setStyleSheet("color:#757575")
        self.idLabel.setObjectName("idLabel")
        self.gridLayout_2.addWidget(self.idLabel, 0, 0, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.nameLineEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout_2.addWidget(self.nameLineEdit, 0, 3, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("color:#757575")
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_2.addWidget(self.nameLabel, 0, 2, 1, 1)
        self.timeLable = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeLable.setFont(font)
        self.timeLable.setStyleSheet("color:#757575")
        self.timeLable.setObjectName("timeLable")
        self.gridLayout_2.addWidget(self.timeLable, 0, 4, 1, 1)
        self.imageLabel = QtWidgets.QLabel(self)
        self.imageLabel.setGeometry(QtCore.QRect(40, 230, 400, 400))
        self.imageLabel.setMinimumSize(QtCore.QSize(400, 400))
        self.imageLabel.setMaximumSize(QtCore.QSize(351, 331))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.lineEdit = QtWidgets.QLineEdit(self)
        self.lineEdit.setGeometry(QtCore.QRect(480, 270, 501, 211))
        self.lineEdit.setObjectName("lineEdit")
        self.remarkLabel = QtWidgets.QLabel(self)
        self.remarkLabel.setGeometry(QtCore.QRect(480, 230, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.remarkLabel.setFont(font)
        self.remarkLabel.setStyleSheet("color:#757575")
        self.remarkLabel.setObjectName("remarkLabel")
        self.feedbackLinkLabel = ClickableLabel(self)
        self.feedbackLinkLabel.setGeometry(QtCore.QRect(480, 610, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.feedbackLinkLabel.setFont(font)
        self.feedbackLinkLabel.setStyleSheet("color:rgb(0, 170, 255)")
        self.feedbackLinkLabel.setObjectName("feedbackLinkLabel")
        self.addErrorLabel(QRect(40, 170, 201, 21), self)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.setValues(registration_id, now_time, response)
        self.topBar.loginButton.clicked.connect(self.gotoHome)
        self.topBar.menuButton.clicked.connect(self.goToMenu)


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("poseVisualizationPage", "Dialog"))
        self.label.setText(_translate("poseVisualizationPage", "Pose visualization"))
        self.uploadButton.setText(_translate("poseVisualizationPage", "Save"))
        self.idLabel.setText(_translate("poseVisualizationPage", "Registration Id"))
        self.nameLabel.setText(_translate("poseVisualizationPage", "Name"))
        self.timeLable.setText(_translate("poseVisualizationPage", "Time"))
        self.remarkLabel.setText(_translate("poseVisualizationPage", "Medical remarks"))
        self.feedbackLinkLabel.setText(_translate("poseVisualizationPage", "<i><u>Provide feedback on this prediction</u></i>"))
    
    def setValues(self, registration_id, now_time, response):
        try:
            data = fetch_data("patients/data", {"_id": registration_id})
            self.idLineEdit.setText(str(registration_id))
            self.nameLineEdit.setText(data["patient_name"])
            self.timeLineEdit.setText(time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(now_time / 1e9)))
            pixmap = QPixmap()
            pixmap.loadFromData(QByteArray(response))
            self.imageLabel.setPixmap(pixmap)
        except Exception as e:
            self.displayErrorMessage(True, "Error fetching data: " + str(e))
