# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration_success.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

from admission_page import PatientAdmissionPage
from image_load_page import ImageUploadPage


class RegistrationSuccessPopup(QtWidgets.QDialog):
    def __init__(self, response, user, parent=None):
        super(RegistrationSuccessPopup, self).__init__(parent)
        self.parent = parent
        self.user = user
        self.setupUi(response)

    def setupUi(self, response):
        self.setObjectName("RegistrationSuccessPopup")
        self.resize(374, 144)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(30, 10, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #757575")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.okButton = QtWidgets.QPushButton(self)
        self.okButton.setGeometry(QtCore.QRect(260, 100, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.okButton.setFont(font)
        self.okButton.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 170, 255)")
        self.okButton.setObjectName("okButton")
        self.setWindowFlags(self.windowFlags() & ~Qt.WindowCloseButtonHint & ~Qt.WindowContextHelpButtonHint)
        self.retranslateUi(response)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.okButton.clicked.connect(lambda: self.patient_admission(response))

    def retranslateUi(self, response):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("RegistrationSuccessPopup", "Registration Success"))
        self.label.setText(_translate("RegistrationSuccessPopup", response))
        self.okButton.setText(_translate("RegistrationSuccessPopup", "Ok"))

    def patient_admission(self, response):
        registration_id = int(response.split(" ")[-1])
        self.accept()
        # patient_admission_page = PatientAdmissionPage(self.parent.parent, registration_id)
        # self.parent.parent.addWidget(patient_admission_page)
        # self.parent.parent.setCurrentIndex(self.parent.parent.currentIndex() + 1)
        image_load_page = ImageUploadPage(self.parent.parent, self.user, registration_id)
        self.parent.parent.addWidget(image_load_page)
        self.parent.parent.setCurrentIndex(self.parent.parent.currentIndex() + 1)
