import base64
import time

import numpy as np
from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtCore import QByteArray, Qt
from PyQt5.QtGui import QPixmap

from components.matplotlib_canvas import MatplotlibCanvas


class SpecificFeedbackView(QtWidgets.QWidget):
    def __init__(self, parent, data):
        super(SpecificFeedbackView, self).__init__(parent)
        self.parent = parent
        self.data = data
        self.setupUi()

    def setupUi(self):
        try:
            self.gridLayoutWidget_6 = QtWidgets.QWidget(self.parent)
            self.gridLayoutWidget_6.setGeometry(QtCore.QRect(530, 14, 351, 221))
            self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
            self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
            self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
            self.gridLayout_7.setObjectName("gridLayout_7")
            self.timeLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.timeLabel.sizePolicy().hasHeightForWidth())
            self.timeLabel.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            self.timeLabel.setFont(font)
            self.timeLabel.setStyleSheet("color:#757575")
            self.timeLabel.setObjectName("timeLabel")
            self.gridLayout_7.addWidget(self.timeLabel, 1, 0, 1, 1)
            self.idLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
            self.idLineEdit.setEnabled(False)
            font = QtGui.QFont()
            font.setPointSize(12)
            self.idLineEdit.setFont(font)
            self.idLineEdit.setStyleSheet("color:#757575")
            self.idLineEdit.setObjectName("idLineEdit")
            self.gridLayout_7.addWidget(self.idLineEdit, 0, 1, 1, 1)
            self.timelIneEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
            self.timelIneEdit.setEnabled(False)
            font = QtGui.QFont()
            font.setPointSize(12)
            self.timelIneEdit.setFont(font)
            self.timelIneEdit.setStyleSheet("color:#757575")
            self.timelIneEdit.setObjectName("timelIneEdit")
            self.gridLayout_7.addWidget(self.timelIneEdit, 1, 1, 1, 1)
            self.idLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.idLabel.sizePolicy().hasHeightForWidth())
            self.idLabel.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            self.idLabel.setFont(font)
            self.idLabel.setStyleSheet("color:#757575")
            self.idLabel.setObjectName("idLabel")
            self.gridLayout_7.addWidget(self.idLabel, 0, 0, 1, 1)
            self.feedbackLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.feedbackLabel.sizePolicy().hasHeightForWidth())
            self.feedbackLabel.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            self.feedbackLabel.setFont(font)
            self.feedbackLabel.setStyleSheet("color:#757575")
            self.feedbackLabel.setObjectName("feedbackLabel")
            self.gridLayout_7.addWidget(self.feedbackLabel, 2, 0, 1, 1)
            self.feedbackPlainTextEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_6)
            self.feedbackPlainTextEdit.setReadOnly(True)
            self.feedbackPlainTextEdit.setObjectName("feedbackPlainTextEdit")
            self.gridLayout_7.addWidget(self.feedbackPlainTextEdit, 2, 1, 1, 1)
            self.feedbackPlainTextEdit.setFont(font)
            self.feedbackPlainTextEdit.setStyleSheet("color:#757575")
            self.userLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.userLabel.sizePolicy().hasHeightForWidth())
            self.userLabel.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(12)
            self.userLabel.setFont(font)
            self.userLabel.setStyleSheet("color:#757575")
            self.userLabel.setObjectName("userLabel")
            self.gridLayout_7.addWidget(self.userLabel, 3, 0, 1, 1)
            self.userLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
            self.userLineEdit.setEnabled(False)
            font = QtGui.QFont()
            font.setPointSize(12)
            self.userLineEdit.setFont(font)
            self.userLineEdit.setStyleSheet("color:#757575")
            self.userLineEdit.setObjectName("userLineEdit")
            self.gridLayout_7.addWidget(self.userLineEdit, 3, 1, 1, 1)


            ###added
            self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.parent)
            self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 300, 183))
            self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
            self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
            self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_3.setObjectName("horizontalLayout_3")
            ############

            self.depthImage = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
            # self.depthImage.setGeometry(QtCore.QRect(10, 10, 141, 181))
            self.depthImage.setObjectName("depthImage")
            self.depthImage.setMinimumSize(QtCore.QSize(140, 181))
            self.depthImage.setMaximumSize(QtCore.QSize(140, 181))
            self.depthCanvas = MatplotlibCanvas(self.depthImage)
            self.horizontalLayout_3.addWidget(self.depthCanvas)

            self.pressureImage = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
            # self.pressureImage.setGeometry(QtCore.QRect(170, 10, 141, 181))
            self.pressureImage.setObjectName("pressureImage")
            self.pressureImage.setMinimumSize(QtCore.QSize(140, 181))
            self.pressureImage.setMaximumSize(QtCore.QSize(140, 181))
            self.pressureCanvas = MatplotlibCanvas(self.pressureImage)
            self.horizontalLayout_3.addWidget(self.pressureCanvas)

            self.outputImage = QtWidgets.QLabel(self.parent)
            self.outputImage.setGeometry(QtCore.QRect(330, 10, 190, 181))
            self.outputImage.setObjectName("outputImage")
            self.depthImageLabel = QtWidgets.QLabel(self.parent)
            self.depthImageLabel.setGeometry(QtCore.QRect(10, 200, 141, 31))
            font = QtGui.QFont()
            font.setPointSize(12)
            self.depthImageLabel.setFont(font)
            self.depthImageLabel.setAlignment(Qt.AlignCenter)
            self.depthImageLabel.setObjectName("depthImageLabel")
            self.pressureImageLabel = QtWidgets.QLabel(self.parent)
            self.pressureImageLabel.setGeometry(QtCore.QRect(170, 200, 141, 31))
            font = QtGui.QFont()
            font.setPointSize(12)
            self.pressureImageLabel.setFont(font)
            self.pressureImageLabel.setAlignment(Qt.AlignCenter)
            self.pressureImageLabel.setObjectName("pressureImageLabel")
            self.outputLabel = QtWidgets.QLabel(self.parent)
            self.outputLabel.setGeometry(QtCore.QRect(350, 200, 141, 31))
            font = QtGui.QFont()
            font.setPointSize(12)
            self.outputLabel.setFont(font)
            self.outputLabel.setAlignment(Qt.AlignCenter)
            self.outputLabel.setObjectName("outputLabel")
            self.retranslateUi()
            self.setValues()
        except Exception as e:
            print(e)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.timeLabel.setText(_translate("viewFeedbackPage", "Time"))
        self.idLabel.setText(_translate("viewFeedbackPage", "Id"))
        self.userLabel.setText(_translate("viewFeedbackPage", "User"))
        self.feedbackLabel.setText(_translate("viewFeedbackPage", "Feedback"))
        self.depthImageLabel.setText(_translate("viewFeedbackPage", "Depth Image"))
        self.pressureImageLabel.setText(_translate("viewFeedbackPage", "Pressure Image"))
        self.outputLabel.setText(_translate("viewFeedbackPage", "Pose Estimation"))

    def setValues(self):
        data = self.data
        self.idLineEdit.setText(str(data["id"]))
        self.timelIneEdit.setText(data["time"])
        self.feedbackPlainTextEdit.setPlainText(data["feedback"])
        self.userLineEdit.setText(data["user"])

        depth = np.array(data["depth"])
        self.depthCanvas.axes.clear()
        self.depthCanvas.draw_idle()
        self.depthCanvas.axes.imshow(depth)
        self.depthCanvas.axes.axis('off')
        self.depthCanvas.draw()

        pressure = np.array(data["pressure"])
        self.pressureCanvas.axes.clear()
        self.pressureCanvas.draw_idle()
        self.pressureCanvas.axes.imshow(pressure)
        self.pressureCanvas.axes.axis('off')
        self.pressureCanvas.draw()

        pixmap = QPixmap()
        pixmap.loadFromData(QByteArray(base64.b64decode(data["visualization"]["$binary"]['base64'])))
        scaled_pixmap = pixmap.scaled(self.outputImage.size(), Qt.KeepAspectRatio, Qt.SmoothTransformation)
        self.outputImage.setAlignment(Qt.AlignCenter)
        self.outputImage.setPixmap(scaled_pixmap)
